In [7]:
import numpy as np

Given a simple problem
$$x + y -z = -3$$
$$x + 2y + z = 7$$
$$2x + y + z = 4$$

In [8]:
 A=np.array([[1,1,-1],
             [1,2,1],
             [2,1,1]])
 B=np.array([[-3],[7],[4]])

In [9]:
#   Ax = B
#   x = inv(A)@B    A=U@D@V.T
#   x = inv(U@D@V.T)@B
#   x = inv(U)@inv(D)@inv(V.T)@B

U, D, VT = np.linalg.svd(A, full_matrices=True)
print(f'U={U} \n\n D={D} \n\n VT={VT}')

U=[[-3.02905447e-01  9.53020614e-01  3.33066907e-16]
 [-6.73887339e-01 -2.14186495e-01 -7.07106781e-01]
 [-6.73887339e-01 -2.14186495e-01  7.07106781e-01]] 

 D=[3.44948974 1.44948974 1.        ] 

 VT=[[-6.73887339e-01 -6.73887339e-01 -3.02905447e-01]
 [ 2.14186495e-01  2.14186495e-01 -9.53020614e-01]
 [ 7.07106781e-01 -7.07106781e-01 -4.99600361e-16]]


In [10]:
U@np.diag(D)@VT

array([[ 1.,  1., -1.],
       [ 1.,  2.,  1.],
       [ 2.,  1.,  1.]])

In [11]:
x = np.linalg.inv(A)@B
x

array([[-1.],
       [ 2.],
       [ 4.]])

In [13]:
x2 = np.linalg.inv(VT)@np.linalg.inv(np.diag(D))@np.linalg.inv(U)@B
x2

array([[-1.],
       [ 2.],
       [ 4.]])