In [1]:
import numpy as np
from numpy.linalg import eigh, norm

In [2]:
A = np.array([[-5,2,3],
              [2,5,1],
              [-3,1,-5]])

In [3]:
A.T

array([[-5,  2, -3],
       [ 2,  5,  1],
       [ 3,  1, -5]])

In [4]:
A.T@A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [5]:
eigh(A.T@A)

(array([25., 39., 39.]),
 array([[ 0.26726124, -0.96362411,  0.        ],
        [ 0.80178373,  0.22237479,  0.5547002 ],
        [-0.53452248, -0.14824986,  0.83205029]]))

In [6]:
ev, V = eigh(A.T@A)

In [7]:
V.T

array([[ 0.26726124,  0.80178373, -0.53452248],
       [-0.96362411,  0.22237479, -0.14824986],
       [ 0.        ,  0.5547002 ,  0.83205029]])

In [8]:
V[0]

array([ 0.26726124, -0.96362411,  0.        ])

In [9]:
u0 = A@V[:,0]/norm(A@V[:,0])
u1 = A@V[:,1]/norm(A@V[:,1])
u2 = A@V[:,2]/norm(A@V[:,2])

In [10]:
U=np.array([u0,u1,u2]).T
U

array([[-0.26726124,  0.77151675,  0.57735027],
       [ 0.80178373, -0.15430335,  0.57735027],
       [ 0.53452248,  0.6172134 , -0.57735027]])

In [11]:
D = np.round(U.T@A@V, decimals=5)
D

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245,  0.   ],
       [-0.   , -0.   ,  6.245]])

In [12]:
#A = U@D@V.T is the SVD
U@D@V.T

array([[-5.00000149,  2.00000098,  3.00000073],
       [ 2.0000003 ,  5.00000057,  1.00000101],
       [-3.00000119,  0.99999963, -5.00000114]])

Try a numpy package for SVD

In [13]:
A2 = np.array([[-5,2,3],
              [2,5,1],
              [-3,1,-5]])

In [14]:
U2, D2, Vh2 = np.linalg.svd(A2, full_matrices=True)

In [15]:
U2

array([[-0.57735027, -0.77151675,  0.26726124],
       [-0.57735027,  0.15430335, -0.80178373],
       [ 0.57735027, -0.6172134 , -0.53452248]])

In [16]:
D2

array([6.244998, 6.244998, 5.      ])

In [17]:
Vh2

array([[-0.        , -0.5547002 , -0.83205029],
       [ 0.96362411, -0.22237479,  0.14824986],
       [-0.26726124, -0.80178373,  0.53452248]])

In [18]:
U2@np.diag(D2)@Vh2

array([[-5.,  2.,  3.],
       [ 2.,  5.,  1.],
       [-3.,  1., -5.]])

Comparison

In [19]:
print('U = ',U,'\n\n U2 =',U2)

U =  [[-0.26726124  0.77151675  0.57735027]
 [ 0.80178373 -0.15430335  0.57735027]
 [ 0.53452248  0.6172134  -0.57735027]] 

 U2 = [[-0.57735027 -0.77151675  0.26726124]
 [-0.57735027  0.15430335 -0.80178373]
 [ 0.57735027 -0.6172134  -0.53452248]]


In [20]:
print('V.T = ',V.T,'\n\n Vh2 =',Vh2)

V.T =  [[ 0.26726124  0.80178373 -0.53452248]
 [-0.96362411  0.22237479 -0.14824986]
 [ 0.          0.5547002   0.83205029]] 

 Vh2 = [[-0.         -0.5547002  -0.83205029]
 [ 0.96362411 -0.22237479  0.14824986]
 [-0.26726124 -0.80178373  0.53452248]]
